---
title: "NFL_Elo_Matchup_Detection"
author: "Maximilian J. Gebauer"
date: "2025-06-12"
output: html_document
---

```{r Setup, include=FALSE, results='hide', warning=FALSE}
knitr::opts_chunk$set(echo = T, fig.width=8, fig.height=4)
options(scipen = 0, digits = 3)  # controls base R output

# Package setup
if(!require("pacman")) install.packages("pacman")

pacman::p_load(tidyverse, dplyr, ggthemes, data.table, lubridate, glmnet,
               GGally, RColorBrewer, ggsci, plotROC, usmap,
               plotly, ggpubr, vistime, coefplot, skimr, car, ggrepel, slider, lubridate,
               tidymodels,ranger,vip,ggplot2, tune,dials,pdp, purrr, stringr, lmtest,
               sandwich)
```

```{r}
#load in the csv files
games_data <- read_csv("/Users/maximiliangebauer/Downloads/games.csv") #game by game information
players_data <- read_csv("/Users/maximiliangebauer/Downloads/players.csv") #player level information
plays_data <- read_csv("/Users/maximiliangebauer/Downloads/plays.csv") #play by play information
game_id <- read_csv("/Users/maximiliangebauer/Downloads/tracking_gameId_2017090700.csv") #tracking data for each play

#return only pass plays
sub_gameid <- game_id %>%
  group_by(gameId,playId) %>%
  filter(any(event %in% c("pass_forward", "pass_shovel", "pass_tipped", "qb_sack", "pass_outcome_touchdown", "pass_arrived", "qb_kneel", "pass_outcome_caught", "pass_outcome_incomplete"))) %>%
  ungroup()

#add in player level data on position
merged_df <- sub_gameid %>%
  left_join(players_data, by = "nflId")

#add in the play data to the tracking + player data
merged2_df <- merged_df %>%
  left_join(plays_data,
            by = c("gameId", "playId"))

#create a defense/offense indicator for players
merged2_df$Side <- as.factor(ifelse(merged2_df$PositionAbbr %in% c("CB", "SS", "FS", "NT", "MLB", "ILB", "OLB", "DE", "DT"), "Defense", "Offense"))

#create indicator for offensive linemen
merged2_df$OL <- as.factor(ifelse(merged2_df$PositionAbbr %in% c("C","G","T"), "OL", "Not_OL"))

#create indicator for possible pass rushers
merged2_df$Possible_Pass_Rusher <- as.factor(ifelse(merged2_df$PositionAbbr %in% c("NT","MLB","ILB", "OLB", "DE", "DT"), "DL", "Not_DL"))

#select out some unnecessary columns to reduce computational cost, can reduce more later for end algorithm
merged3_df <- merged2_df %>%
  dplyr::select(x,y,s,dis,dir,event,nflId,displayName,frame.id,gameId,PositionAbbr,EntryYear,yardlineNumber,yardlineSide,offenseFormation,personnel.offense,personnel.defense,defendersInTheBox,numberOfPassRushers,isPenalty,playDescription, Side, OL, Possible_Pass_Rusher, playId)

#filtering down to one play for testing purposes
sample_play <- merged3_df %>%
  filter(playId == 68)

#filtering down to just the snap and post-snap frames for each player for determining rusher identity and matchups
post_snap_play <- sample_play %>%
  arrange(frame.id) %>%                             
  group_by(nflId) %>%                                
  filter(                                          
    cumsum(!is.na(event) & event == "ball_snap") > 0
  ) %>%
  ungroup()

#setting factors for indicators in case I need them
post_snap_play$Side <- as.factor(post_snap_play$Side)
post_snap_play$OL <- as.factor(post_snap_play$OL)
post_snap_play$Possible_Pass_Rusher <- as.factor(post_snap_play$Possible_Pass_Rusher)

# Set k for number of frames post-snap (inclusive of snap)
k <- 20

#filter for k frames for all defensive players (possible pass rushers)
first_k <- post_snap_play %>%
  filter(Side == "Defense") %>%
  group_by(nflId) %>%
  arrange(frame.id, .by_group = TRUE) %>%
  slice_head(n = k) %>%
  ungroup()

#return line of scrimage value (yards)
yardline <- first_k$yardlineNumber %>% unique()

#Identify which defenders crossed the line of scrimage in the k frames (rusher identification)
rushers_identified <- first_k %>%
  filter(yardline > (110-x)) %>%
  select(nflId) %>%
  unique()

#create a play specific rusher indicator
post_snap_play$Did_Rush <- as.factor(ifelse(post_snap_play$nflId %in% rushers_identified$nflId, "Yes", "No"))

#copy df to avoid overwriting original
post_snap_play2 <- post_snap_play

#compute pairwise Euclidean distances between identified pass rushers and all Olineman 
pairwise_distances <- post_snap_play2 %>%
  inner_join(post_snap_play2, by = "frame.id", suffix = c("_1", "_2")) %>%
  filter(nflId_1 != nflId_2) %>%
  filter(Side_1 != Side_2) %>%
  filter(
    (OL_1 == "OL" & Did_Rush_2 == "Yes") | (OL_2 == "OL" & Did_Rush_1 == "Yes")
  ) %>%
  rowwise() %>%
  filter(nflId_1 < nflId_2) %>%
  mutate(
    dist = sqrt((x_1 - x_2)^2 + (y_1 - y_2)^2)
  ) %>%
  ungroup()

# Compute average distances for each pairing
average_distances <- pairwise_distances %>%
  group_by(nflId_1, nflId_2, Side_1, Side_2) %>%
  summarize(mean_distance = mean(dist), .groups = "drop")

# Create a tidy data frame of pairings
pairings_named <- average_distances %>%
  left_join(post_snap_play2 %>% select(nflId, displayName, PositionAbbr),
            by = c("nflId_1" = "nflId")) %>%
  rename(name_1 = displayName, pos_1 = PositionAbbr) %>%
  left_join(post_snap_play2 %>% select(nflId, displayName, PositionAbbr),
            by = c("nflId_2" = "nflId")) %>%
  rename(name_2 = displayName, pos_2 = PositionAbbr) %>%
  distinct()

#make format of pairings tidy df nicer
tidy_pairings <- pairings_named %>%
  transmute(
    rusher_nflId   = if_else(Side_1 == "Defense", nflId_1, nflId_2),
    rusher_name    = if_else(Side_1 == "Defense", name_1,   name_2),
    rusher_pos     = if_else(Side_1 == "Defense", pos_1,    pos_2),
    ol_nflId       = if_else(Side_1 == "Offense", nflId_1,  nflId_2),
    ol_name        = if_else(Side_1 == "Offense", name_1,   name_2),
    ol_pos         = if_else(Side_1 == "Offense", pos_1,    pos_2),
    mean_distance
  )

#extract number of reported rushers for the play
num_rushers <- post_snap_play$numberOfPassRushers %>% unique()

#return either the top closest pairings if there are more than the number of rushers, or all pairings if there are fewer
tidy_pairings %>%
  group_by(rusher_nflId) %>%
  arrange(-desc(mean_distance), .by_group = TRUE) %>%
  slice_head(n = 1) %>%
  ungroup() %>%
  arrange(-desc(mean_distance)) %>%
  slice_head(n = min(num_rushers, nrow(.)))
```











































































